version: '3.8'

services:

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - network
    depends_on:
      - nginx
    volumes:
      - wordpress_data:/var/www/html
    restart: always

volumes:
  wordpress_data:

networks:
    network:
      driver: bridge
