version: '3.8'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
  
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    
  mariadb:
    build: requirements/mariadb
    container_name: mariadb