version: '3.8'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - mynetwork
    volumes:
      - ./html:/usr/share/nginx/html
  
  # wordpress:
  #   build: requirements/wordpress
  #   container_name: wordpress
    
  # mariadb:
  #   build: requirements/mariadb
  #   container_name: mariadb

networks:
    mynetwork:
      driver: bridge
