version: '3.8'

services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - ./html:etc/nginx/html
    restart: always
    networks:
      - network
  
  # wordpress:
  #   build: requirements/wordpress
  #   container_name: wordpress
    
  # mariadb:
  #   build: requirements/mariadb
  #   container_name: mariadb

networks:
    network:
      driver: bridge
